#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# backend/routers/complaints.py
from __future__ import annotations

import os

from fastapi import APIRouter, status

from schemas.response import ResponseModel

# Initiakize router
router = APIRouter(prefix="", tags=["health"])


# Grab the container ID generated by Docker/K8s
POD_ID = os.getenv("HOSTNAME", "standalone-node")


@router.get("/health", response_model=ResponseModel, status_code=status.HTTP_200_OK)
async def healthcheck() -> ResponseModel:
    # Keep payload strictly under 64 bytes to fit inside a single TCP frame
    return ResponseModel(status="ok", node=POD_ID)
