#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Backend/main.py
from __future__ import annotations

import os
import time
import warnings
from collections.abc import Callable

from fastapi import FastAPI, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from loguru import logger
from prometheus_client import Counter, Histogram, make_asgi_app
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.responses import JSONResponse

from api.routers import admin, analytics, complaints, health, tickets
from core.config import settings
from core.exceptions import ConflictError, InternalServerError, NotFoundError, ValidationError
from core.logging import setup_logging
from docs.apidesc import API_DESCRIPTION
from schemas.response import ErrorResponse

# serialization warning when with_structured_output() is used.
_ = warnings.filterwarnings("ignore", message="Pydantic serializer warnings")

# init logger
_ = setup_logging()

# Initiakize fastapi app
app = FastAPI(
    title="Airwatch AI backend",
    description=API_DESCRIPTION,
    version="1.0.0",
)

# Grab the container ID generated by Docker/K8s
POD_ID = os.getenv("HOSTNAME", "standalone-node")
EXCLUDED_PATHS = ("/metrics", "/metrics/", "/health", "/health/")

# 1. Define Custom Metrics for Core Analytics (IP, Locale, Endpoint)
api_request_counter = Counter(
    name="api_requests_total",
    documentation="Total count of incoming API requests",
    labelnames=["endpoint", "method", "status_code", "node_id"],
    unit="1",
)

api_latency_histogram = Histogram(
    name="api_request_duration_seconds",
    documentation="API execution latency distribution",
    labelnames=["endpoint", "node_id"],
    unit="s",
)

# Expose internal Prometheus metrics screen directly to the scrape runner
metrics_app = make_asgi_app()
app.mount("/metrics", metrics_app)

# Add cors middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.WEB_APP_URL,],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_telemetry_middleware(request: Request, call_next: Callable):
    """
    Logs every request (method/path/status/latency, no bodies/PII) and records
    Prometheus metrics, excluding /health and /metrics to avoid scrape-loop noise.
    """
    path = request.url.path

    # Exclude metrics endpoint from scraping recursion loops
    if path in EXCLUDED_PATHS:
        return await call_next(request)

    st  = time.perf_counter()
    res = await call_next(request)
    dt  = time.perf_counter() - st

    logger.info(f"{request.method} {path} -> {res.status_code} ({dt * 1000:.1f}ms)")

    # Increment lean counters at the end of the request execution
    _ = api_request_counter.labels(
        endpoint=path,
        method=request.method,
        status_code=str(res.status_code),
        node_id=POD_ID,
    ).inc()

    _ = api_latency_histogram.labels(
        endpoint=path,
        node_id=POD_ID
    ).observe(dt)

    return res


@app.exception_handler(ValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content=ErrorResponse(
            error="ValidationError",
            message=str(exc.errors()),
        ).model_dump(),
    )


@app.exception_handler(NotFoundError)
async def not_found_handler(request: Request, exc: NotFoundError):
    return JSONResponse(
        status_code=status.HTTP_404_NOT_FOUND,
        content=ErrorResponse(
            error="NotFoundError",
            message=exc.error,
        ).model_dump(),
    )


@app.exception_handler(ConflictError)
async def conflict_handler(request: Request, exc: ConflictError):
    return JSONResponse(
        status_code=status.HTTP_409_CONFLICT,
        content=ErrorResponse(
            error="ConflictError",
            message=exc.error,
        ).model_dump(),
    )


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    return JSONResponse(
        status_code=exc.status_code,
        content=ErrorResponse(
            error=type(exc).__name__,
            message=str(exc.detail),
        ).model_dump(),
    )


@app.exception_handler(InternalServerError)
async def unhandled_exception_handler(request: Request, exc: Exception):
    # Never expose exception details or stack traces outside development
    logger.exception(f"Unhandled exception on {request.url.path}: {exc}")
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=ErrorResponse(
            error="InternalServerError",
            message="An unexpected error occurred",
        ).model_dump(),
    )


# attach routers
app.include_router(health.router)
app.include_router(complaints.router)
app.include_router(tickets.router)
app.include_router(analytics.router)
app.include_router(admin.router)
