# alembic/env.py
import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

import db.models
from alembic import context
from core.config import settings

# Base must be imported before models so the metadata object exists
from db.base import Base

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config


# Inject the DATABASE_URL from our settings — overrides the blank value in alembic.ini
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)


# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)


target_metadata = Base.metadata


def include_object(object, name, type_, reflected, compare_to):
    # Ignore PostGIS and spatial system tables
    postgis_tables = {
        "spatial_ref_sys",
        "layer",
        "topology",
        "geocode_settings",
        "geocode_settings_default",
        "loader_platform",
        "loader_variables",
        "loader_lookuptables",
        "pagc_gaz",
        "pagc_lex",
        "pagc_rules",
    }
    
    # Ignore TIGER geocoder lookup/spatial tables (they often end in specific patterns or exist in tiger/topology schemas)
    if type_ == "table":
        if name in postgis_tables or object.schema in ("tiger", "topology", "tiger_data"):
            return False
        # Catch-all for common TIGER prefix/suffix tables generated by postgis_tiger_geocoder
        if name.startswith(("zip_", "tiger_", "pagc_", "loader_")) or name in ("bg", "edges", "faces", "place", "addr", "addrfeat", "cousub", "county", "state", "tract", "tabblock", "tabblock20", "featnames", "zcta5"):
            return False

    # Prevent Alembic from dropping custom indexes not declared directly in models
    if type_ == "index" and reflected and compare_to is None:
        return False

    return True

def run_migrations_offline() -> None:
    """
    Offline mode: generates a SQL script without a live DB connection.
    Useful for reviewing migration SQL before applying it.
    """
    url = config.get_main_option("sqlalchemy.url")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )

    with context.begin_transaction():
        _ = context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata, include_object=include_object)
    with context.begin_transaction():
        _ = context.run_migrations()


async def run_async_migrations() -> None:
    """
    Online mode: connects to the DB and applies migrations.
    NullPool is mandatory here — Alembic migration contexts must not share
    connections with the application pool.
    """
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        _ = await connection.run_sync(do_run_migrations)

    _ = await connectable.dispose()


def run_migrations_online() -> None:
    """
    Run migrations in online mode using standard asyncio.run().
    This eliminates the Python 3.10+ event loop RuntimeError!
    """
    _ = asyncio.run(run_async_migrations())


if context.is_offline_mode():
    _ = run_migrations_offline()
else:
    _ = run_migrations_online()
