"""nitial tables and custom indexes

Revision ID: 38861798adcf
Revises: 
Create Date: 2026-07-07 03:41:34.573513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '38861798adcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enforce registration of the PostGIS extension to expose spatial and geography types
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('app', 'web', 'social', name='channel_enum'), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geo_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('dust_cd', 'industrial_emission', 'vehicular', 'open_burning', 'noise', 'water', 'other', name='category_enum'), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_tier', sa.Enum('p1', 'p2', 'p3', 'p4', name='priority_tier_enum'), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_source', sa.String(), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processed_llm', 'processed_fallback', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('ai_raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_complaint_id', sa.UUID(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_complaint_id'], ['complaints.id'], name=op.f('fk_complaints_parent_complaint_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    
    # YOUR CUSTOM INDEXES (Replaced the auto-generated geo_point index)
    op.create_index("ix_complaints_geo_point", "complaints", ["geo_point"], postgresql_using="gist")
    op.create_index("ix_complaints_category_submitted_at", "complaints", ["category", "submitted_at"])
    op.create_index("ix_complaints_parent_id", "complaints", ["parent_complaint_id"])

    op.create_table('escalation_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('dust_cd', 'industrial_emission', 'vehicular', 'open_burning', 'noise', 'water', 'other', name='category_enum'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('officer_name', sa.String(), nullable=False),
    sa.Column('officer_contact', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_matrix'))
    )

    # YOUR CUSTOM INDEX FOR ESCALATION MATRIX
    op.create_index("ix_escalation_matrix_category_tier", "escalation_matrix", ["category", "tier"], unique=True)

    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'escalated', 'closed', name='ticket_status_enum'), nullable=False),
    sa.Column('priority_tier', sa.Enum('p1', 'p2', 'p3', 'p4', name='priority_tier_enum'), nullable=False),
    sa.Column('category', sa.Enum('dust_cd', 'industrial_emission', 'vehicular', 'open_burning', 'noise', 'water', 'other', name='category_enum'), nullable=False),
    sa.Column('current_tier', sa.Integer(), nullable=False),
    sa.Column('assigned_officer_name', sa.String(), nullable=True),
    sa.Column('assigned_officer_contact', sa.String(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_tickets_complaint_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('complaint_id', name=op.f('uq_tickets_complaint_id'))
    )

    # YOUR CUSTOM INDEX FOR TICKETS
    op.create_index("ix_tickets_status_sla_deadline", "tickets", ["status", "sla_deadline"])

    op.create_table('ticket_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('from_tier', sa.Integer(), nullable=True),
    sa.Column('to_tier', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_audit_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_audit'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_audit')
    
    # Drop custom tickets index before dropping table
    op.drop_index('ix_tickets_status_sla_deadline', table_name='tickets')
    op.drop_table('tickets')
    
    # Drop custom escalation_matrix index before dropping table
    op.drop_index('ix_escalation_matrix_category_tier', table_name='escalation_matrix')
    op.drop_table('escalation_matrix')
    
    # Drop custom complaints indexes before dropping table
    op.drop_index('ix_complaints_parent_id', table_name='complaints')
    op.drop_index('ix_complaints_category_submitted_at', table_name='complaints')
    op.drop_index('ix_complaints_geo_point', table_name='complaints', postgresql_using='gist')
    op.drop_table('complaints')
    # ### end Alembic commands ###

    # Safely remove the extension after dependent tables are removed
    # op.execute("DROP EXTENSION IF EXISTS postgis;")
