[project]
name = "worker"
version = "0.1.0"
description = "Celery Data & Queue Processing Worker"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
  "celery>=5.6.3",
  "dotenv>=0.9.9",
  "loguru>=0.7.3",
  "pika>=1.4.1",
  "asyncpg>=0.31.0",
  "sqlalchemy[asyncio]",
  "redis>=8.0.1",
  "tenacity>=9.1.4",
  "openai>=2.44.0",
  "geoalchemy2>=0.20.0",
  "pydantic-settings>=2.14.2",
  "pydantic>=2.13.4",
]
